---
- name: install dependencies
  become: yes
  apt:
    name:
      - python-pip
      - libssl-dev
    state: present

# Query available Molecule versions and split one per line
- name: query available molecule versions
  shell: |
    set -euo pipefail
    pip install molecule== &> >(sed -r 's/[^0-9\\.]*([0-9dev\\.]*)[^0-9\\.]*/\\1\\n/g' | sed '/^$/d') || $(exit 0)
  args:
    executable: /bin/bash
  register: available_molecule_versions
  check_mode: no
  changed_when: no

- name: assert molecule version available
  assert:
    that:
      - 'molecule_version in available_molecule_versions.stdout_lines'

- name: add ansible ppa
  become: yes
  apt_repository:
    repo: 'ppa:ansible/ansible'
    state: present
    codename: '{{ ansible_distribution_release }}'

- name: install ansible
  become: yes
  apt:
    name: ansible
    state: present

# Need to update `wheel` or ansible-lint will get installed without the
# execute bit set (https://bitbucket.org/pypa/wheel/issues/154).
- name: install wheel
  become: yes
  pip:
    name: wheel
    state: present
    extra_args: '--upgrade'

- name: install python docker library
  become: yes
  pip:
    name: docker
    state: present

- name: downgrade pip (pip 10 workaround)
  become: yes
  pip:
    name: pip
    # Workaround pip 10 issue (see https://github.com/pypa/pip/issues/4805)
    version: '9.0.3'
    state: present

- name: install molecule
  become: yes
  pip:
    name: molecule
    version: '{{ molecule_version }}'
    state: present
