---
- name: load version vars
  with_first_found:
    - "../vars/versions/{{ molecule_version }}.yml"
    - ../vars/versions/default.yml
  include_vars: "{{ item }}"

- name: install python-pip
  become: yes
  apt:
    name: python-pip
    state: present

- name: upgrade pip
  become: yes
  pip:
    name: pip
    state: present
    extra_args: '--upgrade'

# Query available Molecule versions and split one per line
- name: query available molecule versions
  shell: "pip install molecule== &> >(sed -r 's/[^0-9\\.]*([0-9dev\\.]*)[^0-9\\.]*/\\1\\n/g' | sed '/^$/d') || $(exit 0)"
  args:
    executable: /bin/bash
  register: available_molecule_versions
  always_run: yes
  changed_when: no

- name: assert molecule version available
  assert:
    that:
      - "molecule_version in available_molecule_versions.stdout_lines"

- name: install apt dependencies
  become: yes
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - libffi-dev
    - libssl-dev
    - python-dev
    - git
    - python-openssl
    - python-yaml
    - python-jinja2
    - python-httplib2
    - python-keyczar
    - python-paramiko
    - python-setuptools
    - python-pkg-resources
    - ruby
    - bundler

- name: add ansible ppa
  become: yes
  apt_repository:
    repo: 'ppa:ansible/ansible'
    state: present

- name: install ansible
  become: yes
  apt:
    name: ansible
    state: present

- name: create download directory
  file:
    path: "{{ molecule_download_dir }}"
    state: directory

- name: download gemfile
  get_url:
    url: "{{ molecule_gem_file_url }}"
    dest: "{{ molecule_download_dir }}/{{ molecule_gem_file_name }}"

- name: install gem dependencies
  become: yes
  command: "bundle install --gemfile={{ molecule_download_dir }}/{{ molecule_gem_file_name }}"
  register: gem_install
  changed_when: "'Installing' in gem_install.stdout"

# Need to update `wheel` or ansible-lint will get installed without the
# execute bit set (https://bitbucket.org/pypa/wheel/issues/154).
- name: install wheel
  become: yes
  pip:
    name: wheel
    state: present
    extra_args: '--upgrade'

- name: install molecule
  become: yes
  pip:
    name: molecule
    version: "{{ molecule_version }}"
    state: present
